# Generated by Django 5.2 on 2025-06-04 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_role_alter_user_id_encryptedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptedfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='encrypted_filename',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
