# Generated by Django 5.2 on 2025-06-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_encryptedfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='encrypted_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
